apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "gpu"
  labels:
    app.kubernetes.io/name: "gpu"
    app.kubernetes.io/version: "1.0.0"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "gpu"
  descriptor:
    links:
      - description: "Open Deepstream"
        url: https://video-analytics-demo-webui