apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8slove.fullname" . }}
  labels:
    {{- include "k8slove.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rtsp
      protocol: TCP
      name: rtsp
  selector:
    {{- include "k8slove.selectorLabels" . | nindent 4 }}
